on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'

jobs:
  retweet:
    runs-on: ubuntu-latest
    environment: env
    name: Retweet
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    
    - name: Install dependencies
      run: npm ci

    - name: Retweet latest
      id: retweet-since-last
      env: 
        CI: true
        API_KEY: ${{ secrets.API_KEY }}
        API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        DROPBOX_OSS_ID: ${{ secrets.DROPBOX_OSS_ID }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SENTIMENT_ANALYSIS_MODEL: ${{ secrets.SENTIMENT_ANALYSIS_MODEL }}
        SENTIMENT_ANALYSIS_MODEL_DEPLOYMENT: ${{ secrets.SENTIMENT_ANALYSIS_MODEL_DEPLOYMENT }}
        SEARCH: ${{ secrets.SEARCH }}
      uses: matt-ramotar/twitter-bot/retweet-action@main

    - name: Log retweets
      env:
        DID_RETWEET: ${{ steps.retweet-since-last.outputs.didRetweet }}
      uses: matt-ramotar/twitter-bot/log-action@main